[package]
name = "MathCAT"
version = "0.1.0"
authors = ["Neil Soiffer <soiffer@alum.mit.edu>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
#sxd-xpath = {path = "../sxd-xpath-0.4.2"}
yaml-rust = "0.4"
lazy_static = "1.4.0"
strum = "0.20"
strum_macros = "0.20"
structopt = "*"
error-chain = "*"
regex = "1.5"
dirs = "3.0"
bitflags = "1.2.1"
phf = { version = "0.8.0", features = ["macros"] }
rand = "0.8.0"
radix_fmt = "1.0.0"
internment = "0.5.4"
log = "0.4.0"
env_logger = "0.8.4"

[build-dependencies]
bitflags = "1.2.1"
phf = { version = "0.8.0", features = ["macros"] }

# intercom = "0.3.0"
# com = "0.4.0"
# windows = "0.3.1"
# bindings = { package = "windows_bindings", path = "bindings" }

# [build-dependencies]
# windows = "0.3.1"

[[bin]]
name = "mathcat"
path = "src/main.rs"

[lib]
name = "libmathcat"
crate-type = ["rlib", "cdylib"]
